//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPrint.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPrint.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;files.associations&quot;: {
        ///    &quot;*.txt&quot;: &quot;text/plain&quot;,
        ///    &quot;*.ans&quot;: &quot;text/ansi&quot;,
        ///    &quot;*.markup&quot;: &quot;markup&quot;,
        ///    &quot;*.html&quot;: &quot;markup&quot;,
        ///    &quot;*.htm&quot;: &quot;markup&quot;,
        ///    &quot;*.html.hl&quot;: &quot;markup&quot;,
        ///    &quot;*.st&quot;: &quot;markup&quot;,
        ///    &quot;*.xht&quot;: &quot;markup&quot;,
        ///    &quot;*.xhtml&quot;: &quot;markup&quot;,
        ///    &quot;*.xml&quot;: &quot;markup&quot;,
        ///    &quot;*.ant&quot;: &quot;markup&quot;,
        ///    &quot;*.axml&quot;: &quot;markup&quot;,
        ///    &quot;*.ccxml&quot;: &quot;markup&quot;,
        ///    &quot;*.clixml&quot;: &quot;markup&quot;,
        ///    &quot;*.cproject&quot;: &quot;markup&quot;,
        ///    &quot;*.csproj&quot;: &quot;markup&quot;,
        ///    &quot;*.ct&quot;: &quot;markup&quot;,
        ///    &quot;*.dita&quot;: &quot;markup&quot;,
        ///    &quot;*.ditamap&quot;: &quot;markup&quot;,
        ///    &quot;*.ditava [rest of string was truncated]&quot;;.
        /// </summary>
        public static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pre[class*=&quot;language-&quot;],
        ///code[class*=&quot;language-&quot;] {
        ///	color: #3b3b3b;
        ///	font-size: 13px;
        ///	text-shadow: none;
        ///	font-family: Consolas, Monaco, &apos;Andale Mono&apos;, &apos;Ubuntu Mono&apos;, monospace;
        ///	direction: ltr;
        ///	text-align: left;
        ///	white-space: pre;
        ///	word-spacing: normal;
        ///	word-break: normal;
        ///	line-height: 1.5;
        ///	-moz-tab-size: 4;
        ///	-o-tab-size: 4;
        ///	tab-size: 4;
        ///	-webkit-hyphens: none;
        ///	-moz-hyphens: none;
        ///	-ms-hyphens: none;
        ///	hyphens: none;
        ///}
        ///
        ///pre[class*=&quot;language-&quot;]::selection,
        ///code[class*=&quot;language-&quot;]::selection {
        ///	text- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string prism_winprint {
            get {
                return ResourceManager.GetString("prism_winprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* These style override Prism built-in (and any provided theme), 
        ///   optimizing for rendering for print. E.g. Colored backgrounds
        ///    make no sense when printing. Also turns off some stuff 
        ///    litehtml does not support correctly.
        ///*/
        ///code[class*=&quot;language-&quot;],
        ///pre[class*=&quot;language-&quot;] {
        ///    /* no backgrond 
        ///    background: none;*/
        ///    /* linehtml only supports white-space: pre-wrap. word-break: break-all are not yet supported.*/
        ///    /* Relevant docs:
        ///        white-space - https://developer.mozilla. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string prism_winprint_overrides {
            get {
                return ResourceManager.GetString("prism_winprint_overrides", resourceCulture);
            }
        }
    }
}
