//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPrint.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPrint.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;files.associations&quot;: {
        ///    &quot;*.markup&quot;: &quot;markup&quot;,
        ///    &quot;*.html&quot;: &quot;markup&quot;,
        ///    &quot;*.htm&quot;: &quot;markup&quot;,
        ///    &quot;*.html.hl&quot;: &quot;markup&quot;,
        ///    &quot;*.st&quot;: &quot;markup&quot;,
        ///    &quot;*.xht&quot;: &quot;markup&quot;,
        ///    &quot;*.xhtml&quot;: &quot;markup&quot;,
        ///    &quot;*.xml&quot;: &quot;markup&quot;,
        ///    &quot;*.ant&quot;: &quot;markup&quot;,
        ///    &quot;*.axml&quot;: &quot;markup&quot;,
        ///    &quot;*.ccxml&quot;: &quot;markup&quot;,
        ///    &quot;*.clixml&quot;: &quot;markup&quot;,
        ///    &quot;*.cproject&quot;: &quot;markup&quot;,
        ///    &quot;*.csproj&quot;: &quot;markup&quot;,
        ///    &quot;*.ct&quot;: &quot;markup&quot;,
        ///    &quot;*.dita&quot;: &quot;markup&quot;,
        ///    &quot;*.ditamap&quot;: &quot;markup&quot;,
        ///    &quot;*.ditaval&quot;: &quot;markup&quot;,
        ///    &quot;*.dll.config&quot;: &quot;markup&quot;,
        ///    &quot;*.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * prism.js WinPrint theme 
        /// * Based on prism-coy.css
        /// * @author Charlie Kindel
        /// */
        ///
        ///code[class*=&quot;language-&quot;],
        ///pre[class*=&quot;language-&quot;] {
        ///    color: black;
        ///    /* *font-family: Consolas, Monaco, &apos;Andale Mono&apos;, &apos;Ubuntu Mono&apos;, monospace; */
        ///    /* HACK: note &apos;winprint&apos; font at end. */
        ///    font-family: &apos;Cascadia Code&apos;, Consolas, Monaco, &apos;Andale Mono&apos;, &apos;Ubuntu Mono&apos;, monospace, winprint;
        ///    font-size: 7pt;
        ///}
        ///
        ///code[class*=&quot;language&quot;] {
        ///    max-height: inherit;
        ///    height: inherit;
        ///    displ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string prism_winprint {
            get {
                return ResourceManager.GetString("prism_winprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* These style override Prism built-in (and any provided theme), 
        ///   optimizing for rendering for print. E.g. Colored backgrounds
        ///    make no sense when printing. Also turns off some stuff 
        ///    litehtml does not support correctly.
        ///*/
        ///code[class*=&quot;language-&quot;],
        ///pre[class*=&quot;language-&quot;] {
        ///    /* no backgrond 
        ///    background: none;*/
        ///    /* linehtml only supports white-space: pre-wrap. word-break: break-all are not yet supported.*/
        ///    /* Relevant docs:
        ///        white-space - https://developer.mozilla. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string prism_winprint_overrides {
            get {
                return ResourceManager.GetString("prism_winprint_overrides", resourceCulture);
            }
        }
    }
}
