// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
namespace WinPrint.Core.Services {
    /// <summary>
    /// </summary>
    public static class TelemetryService {
        public const string Key = "ac8d0deb-7936-4bc3-8b84-53f7d351e5a9";
   }
}
