title: WinPrint 2
description: winprint - Advanced source code and text file printing for PowerShell.
logo: https://tig.github.io/winprint/winprint-icon.png
theme: jekyll-theme-dinky
google_analytics: UA-4945529-9
github:
  install_url: https://github.com/tig/winprint/releases
