//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPrint.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPrint.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;files.associations&quot;: {
        ///    &quot;*.markup&quot;: &quot;markup&quot;,
        ///    &quot;*.html&quot;: &quot;markup&quot;,
        ///    &quot;*.htm&quot;: &quot;markup&quot;,
        ///    &quot;*.html.hl&quot;: &quot;markup&quot;,
        ///    &quot;*.st&quot;: &quot;markup&quot;,
        ///    &quot;*.xht&quot;: &quot;markup&quot;,
        ///    &quot;*.xhtml&quot;: &quot;markup&quot;,
        ///    &quot;*.xml&quot;: &quot;markup&quot;,
        ///    &quot;*.ant&quot;: &quot;markup&quot;,
        ///    &quot;*.axml&quot;: &quot;markup&quot;,
        ///    &quot;*.ccxml&quot;: &quot;markup&quot;,
        ///    &quot;*.clixml&quot;: &quot;markup&quot;,
        ///    &quot;*.cproject&quot;: &quot;markup&quot;,
        ///    &quot;*.csproj&quot;: &quot;markup&quot;,
        ///    &quot;*.ct&quot;: &quot;markup&quot;,
        ///    &quot;*.dita&quot;: &quot;markup&quot;,
        ///    &quot;*.ditamap&quot;: &quot;markup&quot;,
        ///    &quot;*.ditaval&quot;: &quot;markup&quot;,
        ///    &quot;*.dll.config&quot;: &quot;markup&quot;,
        ///    &quot;*.fi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * prism.js Coy theme for JavaScript, CoffeeScript, CSS and HTML
        /// * Based on https://github.com/tshedor/workshop-wp-theme (Example: http://workshop.kansan.com/category/sessions/basics or http://workshop.timshedor.com/category/sessions/basics);
        /// * @author Tim  Shedor
        /// */
        ///
        ///code[class*=&quot;language-&quot;],
        ///pre[class*=&quot;language-&quot;] {
        ///	color: black;
        ///	background: none;
        ///	font-family: Consolas, Monaco, &apos;Andale Mono&apos;, &apos;Ubuntu Mono&apos;, monospace;
        ///	font-size: 1em;
        ///	text-align: left;
        ///	white-space: pre;
        ///	word-sp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string prism_coy {
            get {
                return ResourceManager.GetString("prism_coy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code[class*=&quot;language-&quot;],
        ///pre[class*=&quot;language-&quot;] {
        ///    background: none;
        ///    font-family: &apos;Cascadia Code&apos;, Consolas, Monaco, &apos;Andale Mono&apos;, &apos;Ubuntu Mono&apos;, monospace, winprint;
        ///    font-size: 10pt;
        ///    white-space: pre-wrap;
        ///    word-wrap: break-word;
        ///    word-break: break-all;
        ///    line-height:normal;
        ///    padding: 0;
        ///    margin: 0;
        ///}
        ///
        ////* Code blocks */
        ///pre[class*=&quot;language-&quot;] {
        ///    margin: 0;
        ///    overflow: visible;
        ///    padding: 0;
        ///}
        ///
        ////* Background &amp; border */
        ///pre[class*=&quot;language-&quot;] &gt; c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string prism_winprint_overrides {
            get {
                return ResourceManager.GetString("prism_winprint_overrides", resourceCulture);
            }
        }
    }
}
