//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPrint.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPrint.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;file.associations&quot;: {
        ///        &quot;*.myphp&quot;: &quot;php&quot;
        ///    },
        ///    &quot;languages&quot;: [
        ///        {
        ///            &quot;id&quot;: &quot;markup&quot;,
        ///            &quot;title&quot;: &quot;Markup&quot;,
        ///            &quot;aliases&quot;: [
        ///                &quot;html&quot;,
        ///                &quot;xml&quot;,
        ///                &quot;svg&quot;,
        ///                &quot;mathml&quot;
        ///            ],
        ///            &quot;extensions&quot;: [
        ///                &quot;.markup&quot;,
        ///                &quot;.html&quot;,
        ///                &quot;.xml&quot;,
        ///                &quot;.svg&quot;,
        ///                &quot;.mathml&quot;
        ///            ]
        ///        },
        ///        {
        ///            &quot;id&quot;: &quot;css&quot;,
        ///            &quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code[class*=&quot;language-&quot;],
        ///pre[class*=&quot;language-&quot;] {
        ///	background: none;
        ///	font-family: &apos;Cascadia Code&apos;, Consolas, Monaco, &apos;Andale Mono&apos;, &apos;Ubuntu Mono&apos;, monospace;
        ///	font-size: 10pt;
        ///	white-space: pre-wrap;
        ///	word-wrap: break-word;
        ///	word-break: break-all;
        ///}
        ///
        ////* Code blocks */
        ///pre[class*=&quot;language-&quot;] {
        ///	margin: 0;
        ///	overflow: visible;
        ///	padding: 0;
        ///}
        ///
        ///pre[class*=&quot;language-&quot;]&gt;code {
        ///	position: relative;
        ///	border-left: 0px solid black;
        ///}
        ///
        ///code[class*=&quot;language&quot;] {
        ///	max-height: inherit;
        ///	padding [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string prism_winprint_overrides {
            get {
                return ResourceManager.GetString("prism_winprint_overrides", resourceCulture);
            }
        }
    }
}
