name: .NET Core

on:
  push:
    branches: [ main, v2.1 ]
  pull_request:
    branches: [ main, v2.1 ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        # Checkout libvt100 & litehtml
        submodules: 'recursive'

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Restore packages
    - name: Restore
      run: msbuild src/WinPrint.slnx /t:Restore /p:Configuration=Release /p:Platform=x64

    # Build
    - name: Build
      run: msbuild src/WinPrint.slnx /p:Configuration=Release /p:Platform=x64 /p:DefineConstants="CI_BUILD"

    # Run Tests
    - name: Test
      run: dotnet test tests/WinPrint.Core.UnitTests --configuration Release -p:Platform=x64 --no-build --verbosity normal /p:DefineConstants="CI_BUILD"
